spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      rocketmq:
        binder:
          # RocketMQ 服务器地址
          namesrv-addr: 192.168.245.129:9876
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        input: {destination: test-topic, content-type: application/json, group: test-group}

server:
  port: 9094

management:
  endpoints:
    web:
      exposure:
        include: '*'
